"""adding base model

Revision ID: 7eed5c05ef37
Revises: 438ce6d4af4b
Create Date: 2021-05-08 21:21:42.347267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eed5c05ef37'
down_revision = '438ce6d4af4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Artist', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('Venue', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Venue', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'updated_at')
    op.drop_column('Venue', 'created_at')
    op.drop_column('Artist', 'updated_at')
    op.drop_column('Artist', 'created_at')
    # ### end Alembic commands ###
